In [2]:
%matplotlib inline

In [3]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
train_set = pd.read_csv('train.csv')
test_set = pd.read_csv('test.csv')

In [31]:
from sklearn import cross_validation
train_data, validation_data = cross_validation.train_test_split(
        train_set,
        train_size = 0.8, 
        random_state  = 0)
train_data.index = np.arange(0,len(train_data.index))
validation_data.index = np.arange(0,len(validation_data.index))

In [33]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=25, n_jobs=5)
clf.fit(train_data[['x','y']], train_data.place_id) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=5, n_neighbors=25, p=2,
           weights='uniform')

In [34]:
neighbors = clf.kneighbors(validation_data[['x','y']])

In [46]:
validation_prediction = pd.DataFrame(validation_data.row_id)
validation_prediction['place_id'] = ''

In [63]:
neighborsdf = pd.DataFrame(neighbors[1])

In [66]:
neighborsdf.head()

0         1         2         3         4         5         6   \
0  12622259   3004377  21221593  22350190  16486461  18309455   9460356   
1  18669727  12568605  11811558    498004   9306679  17544658  19953536   
2  22365157    537459   8207126   9420933  15928222  14529463   9224900   
3   9634669  17668195   1349151  11039372   2298315   8226067   9792662   
4   1004932   7484416  20599253  11207867   1740764   8108637   4301271   

         7         8         9     ...           15        16        17  \
0     19571  10810295   9739973    ...      4520747  20783887  13534406   
1  16690181   3950112   3112688    ...     13236445  11170928   3092527   
2  15546193  21769676  17331511    ...     16773448   3002705   9643401   
3   4830871   4452056  18795723    ...      2700290    307109   5327047   
4  17741044   2336448   2768219    ...     11476730   5158578  21884737   

         18       19        20        21        22        23        24  
0  17058773   980840  19102243  12544974   9550525  12606175  15570110  
1    979948  8997278  20968932  20268348   4084849  20331712  14439506  
2  16004518  1411243  10822823   8314541  16480328   8175485  14746437  
3  14908809  1029638   8069049   1204151  16403597    801940  18187494  
4  20051222  8066187  11146269  22028565  16900030  15258341    311946  

[5 rows x 25 columns]

In [86]:
place_id_array = ['place_id'] * len(neighborsdf[0].index)
for i in np.arange(0,25):
    lookup_result = train_data.lookup(neighborsdf[i], place_id_array)
    new_label = 'p' + i.astype(str)
    neighborsdf[new_label] = lookup_result

In [91]:
for i in np.arange(0,25):
    del neighborsdf[i]

In [92]:
neighborsdf.head()

p0          p1          p2          p3          p4          p5  \
0  8698978483  4870129041  8698978483  1480179729  3560133457  7328335720   
1  4642326904  4642326904  7045447773  4642326904  4642326904  3683524998   
2  2562148330  5103363855  4201331222  2562148330  2562148330  2809692309   
3  1385081482  1385081482  5172648263  2398604745  1656828008  9353445626   
4  3944068460  5077523021  1295487215  7595705627  1295487215  1295487215   

           p6          p7          p8          p9     ...             p15  \
0  8698978483  1480179729  2521332476  1480179729     ...      8698978483   
1  4642326904  3965589824  9213926120  5193185323     ...      6542798770   
2  8017436759  2562148330  7497331127  7874646502     ...      2562148330   
3  9353445626  9353445626  8277962573  1662809061     ...      4225455186   
4  2884561324  1295487215  7266645604  7266645604     ...      2884561324   

          p16         p17         p18         p19         p20         p21  \
0  7328335720  1480179729  7328335720  1480179729  8698978483  9951984946   
1  4642326904  4802499567  4802499567  5193185323  7639314209  4642326904   
2  2562148330  4422962999  2562148330  5103363855  2562148330  5103363855   
3  7896404869  8018960669  3517644736  1662809061  7087122536  1662809061   
4  1976396737  1295487215  9183417071  7266645604  2853949249  9652985100   

          p22         p23         p24  
0  2521332476  4870129041  8698978483  
1  4642326904  6542798770  4642326904  
2  8392124776  1005481397  2562148330  
3  5426545951  1656828008  6874503774  
4  3944357875  7266645604  2884561324  

[5 rows x 25 columns]

In [100]:
neighborsdf['result'] = ''

In [80]:
lookup_result

array([  8.69897848e+09,   4.64232690e+09,   2.56214833e+09, ...,
         2.64837435e+09,   6.30962964e+09,   6.64222509e+09])

In [81]:
lookup_result[0]

8698978483.0

In [93]:
train_data[train_data.index == 9634669]

row_id       x      y  accuracy    time    place_id
9634669  6221102  3.1468  9.295         5  747383  1385081482

In [82]:
train_data[train_data.index == 18669727]

row_id       x       y  accuracy    time    place_id
18669727  7140831  7.1489  3.4435       176  598331  4642326904

In [35]:
neighbors[0][0]

array([ 0.0005099 ,  0.00072801,  0.00082462,  0.00102956,  0.00111803,
        0.00126491,  0.00126491,  0.0013    ,  0.00131529,  0.0014    ,
        0.00152315,  0.00158114,  0.00170294,  0.00226716,  0.00248395,
        0.00272947,  0.0027313 ,  0.00290689,  0.00296142,  0.00308058,
        0.00308869,  0.00311127,  0.00319531,  0.0032249 ,  0.00332415])

In [36]:
neighbors[1][0]

array([12622259,  3004377, 21221593, 22350190, 16486461, 18309455,
        9460356,    19571, 10810295,  9739973,   874961, 16365094,
        6411481,  8212358,  4593895,  4520747, 20783887, 13534406,
       17058773,   980840, 19102243, 12544974,  9550525, 12606175, 15570110], dtype=int64)

In [37]:
ndf = train_data[train_data.index.isin(neighbors[1][0])]

In [60]:
len(ndf.place_id.value_counts())

9

In [58]:
ndf.place_id.value_counts().index[0].astype(str) + ' ' + ndf.place_id.value_counts().index[1].astype(str)

'8698978483 1480179729'

In [28]:
n = clf.kneighbors([[7.1783,7.2541]])

In [29]:
n

(array([[ 0.        ,  0.00161245,  0.00170294,  0.0018868 ,  0.00197231,
          0.00208087,  0.00219545,  0.00234307,  0.00240208,  0.00254951,
          0.00274591,  0.00277849,  0.00311448,  0.00353553,  0.0037    ,
          0.00376431,  0.00386005,  0.00390128,  0.00399625,  0.00402492,
          0.00403113,  0.00403609,  0.004245  ,  0.00430116,  0.00440114]]),
 array([[       1,  5851764, 20299954, 17279785, 13936407,  6917442,
         18705103, 17415528,  7964344,  9893491, 22547026, 21355351,
          8451655,  5615439, 13850709,  5785855,  9258512, 18083233,
          9943550, 19874621, 22570072,  3579182,  9027060,  4289469,
         21476159]], dtype=int64))

In [13]:
for neighbor in neighbors:
    train_data[train_data.place_id.isin(neighbor)].place_id

In [99]:
result = neigh.kneighbors(test_set[['x','y']], 3, return_distance=False)
resultDF = pd.DataFrame(result, columns=['p1','p2','p3'])
resultDF['place_id'] = resultDF['p1'].astype(str) + " " + \
                     resultDF['p2'].astype(str) + " " + \
                     resultDF['p3'].astype(str)

del resultDF['p1']
del resultDF['p2']
del resultDF['p3']
resultDF.to_csv('result.csv', index=True, index_label='row_id')